---
- name: "Install nftables"
  apt:
    name: nftables
    install_recommends: false
    update_cache: true
  notify: restart_nftables

- name: "Create /etc/nftables.conf file"
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    mode: "0644"
    validate: "/usr/sbin/nft -c -f %s"
  notify: restart_nftables

- meta: flush_handlers
