---
- name: "Restart haproxy service"
  systemd:
    state: restarted
    enabled: true
    daemon_reload: true
    name: haproxy
  listen: restart_haproxy

- name: "Reload haproxy service"
  shell: echo 'reload' | socat unix-connect:/run/haproxy-master.sock stdio
  listen: reload_haproxy
