---
- hosts: [balancer_nodes, master_nodes]
  become: true
  tasks:
    - name: "Gather facts"
      setup:
        gather_subset:
          - "!all"
          - "!any"
          - network

- hosts: [balancer_nodes]
  become: true
  roles:
    - bootstrap_os
    - nftables
    - haproxy
